version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20

  pre_build:
    commands:
      # AWS 계정 로그인
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      # 설정 파일 디렉토리 생성
      - echo Creating resources directory...
      - mkdir -p src/main/resources

      # application.yml 파일들을 CodeCommit에서 가져오기
      - echo Fetching configuration files from CodeCommit...
      - aws codecommit get-file --repository-name $YOUR_REPO_NAME --file-path application.yml --output text --query fileContent > src/main/resources/application.yml
      - aws codecommit get-file --repository-name $YOUR_REPO_NAME --file-path application-dev.yml --output text --query fileContent > src/main/resources/application-dev.yml

      # 파일 존재 확인
      - echo "=== Checking config files ==="
      - ls -la src/main/resources/

      # 이미지 태그 설정 (빌드 번호 사용)
      - echo Setting image tag...
      - IMAGE_TAG=v${CODEBUILD_BUILD_NUMBER}
      - echo "Building version": $IMAGE_TAG
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME

  build:
    commands:
      # Docker 이미지 빌드
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      # ECR에 이미지 푸시
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest

      # 현재 태스크 정의를 가져와서 새 이미지로 업데이트
      - echo Creating new task definition revision...
      - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition $ECS_TASK_FAMILY --region $AWS_DEFAULT_REGION)
      - NEW_TASK_DEF=$(echo $TASK_DEFINITION | jq --arg IMAGE "$REPOSITORY_URI:$IMAGE_TAG" '.taskDefinition | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy) | .containerDefinitions[0].image = $IMAGE')
      - echo "New task definition:"
      - echo $NEW_TASK_DEF
      - NEW_TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEF" | jq -r '.taskDefinition.taskDefinitionArn')

      # ECS 서비스 업데이트 (롤링 배포)
      - echo Updating ECS service...
      - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --task-definition $NEW_TASK_DEF_ARN --force-new-deployment
      - echo "Updated to image $REPOSITORY_URI:$IMAGE_TAG"

      # 배포에 필요한 정보를 artifacts로 저장
      - echo "Creating artifacts..."
      - printf '{"ImageURI":"%s","ImageTag":"%s"}' $REPOSITORY_URI:$IMAGE_TAG $IMAGE_TAG > imageDefinitions.json
      - cat imageDefinitions.json

      - echo Build completed on `date`

artifacts:
  files:
    - imageDefinitions.json
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'